### ISSUE TITLE
Bug: Black holes don't suck

### ISSUE THREAD

**Issue by DizzyKungFu** [artemis-sbs/LegendaryMissions#80]
In 2.8, I'm 100% sure black holes pulled in nearby asteroids and vanished them. Not entirely sure if nebulas were susceptible to sucking in 2.8. Anyway, in Cosmos, the only thing that seems to get sucked is player ships. I spawned a bunch of asteroids and nebulas right next to a black hole (like distance < 2000) and watched for like 15 minutes... nothing happened, nothing moved.

**Comment by DizzyKungFu** [comment]
I'm certain the black holes in 2.8 could also pull in bases and NPC ships.

**Comment by dougreichard** [comment]
This is not an issue. The black hole needs to be created with greater force.

If you are using terrain_spawn_black_hole try changing the settings to get the desired suckage.

``` py
def terrain_spawn_black_hole(x,y,z, gravity_radius= 1500, gravity_strength=1.0, turbulence_strength= 1.0, collision_damage=200):
```

If you are creating the object yourself the same values are data_set / blob values.

``` py
    bh = to_object(terrain_spawn(x,y,z, r_name, "#,black_hole", "maelstrom", "behav_maelstrom"))
    bh.engine_object.exclusion_radius = 100 # event horizon
    blob = bh.data_set
    blob.set("gravity_radius", gravity_radius, 0)
    blob.set("gravity_strength", gravity_strength, 0)
    blob.set("turbulence_strength", turbulence_strength, 0)
    blob.set("collision_damage", collision_damage, 0)
```

**Comment by dougreichard** [comment]
I suppose the LegendaryMissions black holes could suck more.

I've updated the defaults for those and the prefab to radius = 5000 strength 4 (assuming that means warp 4 is needed, and turbulence 2.) 

Maybe strength should be 5.  

fixed in v1.1.0

**Comment by quaris628** [comment]
I agree with @DizzyKungFu that this isn't fixed. I can still reproduce it in 1.3.0. I think this issue should be reopened.

Also, this bug not only applies to asteroids, but mines and wrecks as well.

Whether black holes should suck nebula seems debatable to me. Their gas really should be physically affected by gravity. But on the other hand, nebula "objects" are so large that deleting them the instant they touch the event horizon won't look very realistic, and I find that nebula limiting your warp speed around black holes makes for a more interesting challenge which would be nice to keep in the game.
